#!/bin/bash

apt-get update

apt-get install -y \
  apt-transport-https \
  build-essential \
  ca-certificates \
  curl \
  exuberant-ctags \
  gettext \
  git \
  gnupg \
  graphviz \
  neovim \
  openjdk-8-jdk \
  pgadmin3 \
  pgcli \
  software-properties-common \
  tmux \
  tree \
  unzip \
  wget \
  zip