#!/bin/bash

mkdir -p ~/.config/nvim

python3 -m pip install virtualenv
python3 -m virtualenv -p python3 ~/.config/nvim/env

source ~/.config/nvim/env/bin/activate
pip install neovim jedi psutil setproctitle yapf
deactivate

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sed '/call plug#end/q' dotfiles/init.vim > ~/.config/nvim/init.vim
nvim -c ':PlugInstall' -c ':qall'
rm ~/.config/nvim/init.vim
cp dotfiles/init.vim ~/.config/nvim/